### PR TITLE
Journal week 3

### PR DESCRIPTION
**Pull request by ericquayson**

### CODE REVIEW

**Comment by boshnivolo** [comment]
Great Journal! I also had to face off with my own understanding of CSS last week. But I agree, I want to learn how they interact and work together too :+1:

**Comment by jeremyrist** [comment]
:+1: You seem to have a really good grasp of the vocabulary here, I'm envious. Teach me sensei haha

**Comment by karjac14** [comment]
Great wrapping up of Week 3. :+1:

**Comment by jeremyrist** [comment]
:+1: I love your writing voice man, well said. Don't forget to throw this PR link in your Issue comments!

**Comment by boshnivolo** [comment]
I really enjoyed reading about your personal experience with adhering new CSS knowledge into your work here in FEE.
:+1: 
:100: 
:gem: 
This journal was straight :fire:

**Comment by jeffworley** [comment]
Looks solid.  I enjoy your writing style and like your tutorial topic.  :+1:

**Comment by drumslayert** [comment]
great job Eric! :+1:

**Pull request merged**
